# tasks file for sysctl
---
- name: set sysctl settings
  become: true
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: true
    state: "{{ item.state | default('present') }}"
  with_items: "{{ sysctl_settings }}"
  tags:
    - configuration
    - sysctl
    - sysctl-settings
