# tasks file for sysctl
---
- name: set sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: sysctl_settings
  notify: reload sysctl
  tags:
    - configuration
    - sysctl
    - sysctl-settings
